### ISSUE TITLE
Potential Violation Detected

### ISSUE THREAD

**Issue by assignguard-support** [garcias/Chem122-2016#1]
Hey garcias!

This repository has been flagged as containing material which potentially infringes upon an academic copyright or an institution's academic integrity policies.

At your earliest convenience, please do one of the following:
  - disable public access to your repository see [repository access settings](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/setting-repository-visibility)
  - remove any content could be in violation of copyright law
  - remove any content could be in violation of an institution's academic integrity policy

Please feel free to continue any discussion here. Thanks!

**Comment by assignguard-support** [comment]
:wave: gentle reminder!

**Comment by garcias** [comment]
I assert that the entire content of this repository is **my original work**. I added LICENSE.txt to clarify the terms of reuse under CC-BY-4.0.

I advise that you review [GitHub's guidelines for Content Removal](https://docs.github.com/en/site-policy/content-removal-policies/guide-to-submitting-a-dmca-takedown-notice). While this Issue is not a formal takedown notice, you are using it as part of the process (as described under [Ask Nicely First](https://docs.github.com/en/site-policy/content-removal-policies/guide-to-submitting-a-dmca-takedown-notice#before-you-start)). As currently implemented, your Issue fails to comply with two guidelines:

- > Send In The Correct Request. We can only accept DMCA takedown notices for works that are protected by copyright, and _that identify a specific copyrightable work_ [emphasis mine].
  - This Issue does not identify specific copyrightable work.
- > No Bots. You should have a trained professional evaluate the facts of every takedown notice you send. If you are outsourcing your efforts to a third party, make sure you know how they operate, and make sure they are not using automated bots to submit complaints in bulk. These complaints are often invalid and processing them results in needlessly taking down projects!
  - The user named `assign-guard` has generated hundreds of issues with identical text within the month of November, which is consistent with bot activity.
